services:
  - type: web
    name: UnlimComm
    env: python
    plan: free
    region: oregon
    runtime: python-3.10.12
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
